FROM python:3
RUN which python
RUN python --version
RUN pip install --upgrade pip
RUN pip --version
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
ADD cortex /cortex
EXPOSE 8080
CMD python -m cortex.gui run-server --host '0.0.0.0' 'mongodb://my_mongo:27017'
