# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cortex_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cortex_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63ortex_server.proto\"\x8a\x01\n\x07TheUser\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\r\x12\x1f\n\x06gender\x18\x04 \x01(\x0e\x32\x0f.TheUser.Gender\")\n\x06Gender\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\t\n\x05OTHER\x10\x02\"\xa1\x01\n\x0bTheSnapshot\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\x04\x12\x16\n\x04pose\x18\x02 \x01(\x0b\x32\x08.ThePose\x12#\n\x0b\x63olor_image\x18\x03 \x01(\x0b\x32\x0e.TheColorImage\x12#\n\x0b\x64\x65pth_image\x18\x04 \x01(\x0b\x32\x0e.TheDepthImage\x12\x1e\n\x08\x66\x65\x65lings\x18\x05 \x01(\x0b\x32\x0c.TheFeelings\"\xcd\x01\n\x07ThePose\x12,\n\x0btranslation\x18\x01 \x01(\x0b\x32\x17.ThePose.TheTranslation\x12&\n\x08rotation\x18\x02 \x01(\x0b\x32\x14.ThePose.TheRotation\x1a\x31\n\x0eTheTranslation\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a\x39\n\x0bTheRotation\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"<\n\rTheColorImage\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"<\n\rTheDepthImage\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\"T\n\x0bTheFeelings\x12\x0e\n\x06hunger\x18\x01 \x01(\x02\x12\x0e\n\x06thirst\x18\x02 \x01(\x02\x12\x12\n\nexhaustion\x18\x03 \x01(\x02\x12\x11\n\thappiness\x18\x04 \x01(\x02\x62\x06proto3')
)



_THEUSER_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='TheUser.Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MALE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=121,
  serialized_end=162,
)
_sym_db.RegisterEnumDescriptor(_THEUSER_GENDER)


_THEUSER = _descriptor.Descriptor(
  name='TheUser',
  full_name='TheUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='TheUser.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='TheUser.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='TheUser.birthday', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='TheUser.gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _THEUSER_GENDER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=162,
)


_THESNAPSHOT = _descriptor.Descriptor(
  name='TheSnapshot',
  full_name='TheSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='TheSnapshot.datetime', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='TheSnapshot.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color_image', full_name='TheSnapshot.color_image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_image', full_name='TheSnapshot.depth_image', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feelings', full_name='TheSnapshot.feelings', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=326,
)


_THEPOSE_THETRANSLATION = _descriptor.Descriptor(
  name='TheTranslation',
  full_name='ThePose.TheTranslation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ThePose.TheTranslation.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ThePose.TheTranslation.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='ThePose.TheTranslation.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=475,
)

_THEPOSE_THEROTATION = _descriptor.Descriptor(
  name='TheRotation',
  full_name='ThePose.TheRotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ThePose.TheRotation.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ThePose.TheRotation.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='ThePose.TheRotation.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='ThePose.TheRotation.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=534,
)

_THEPOSE = _descriptor.Descriptor(
  name='ThePose',
  full_name='ThePose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='ThePose.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='ThePose.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_THEPOSE_THETRANSLATION, _THEPOSE_THEROTATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=534,
)


_THECOLORIMAGE = _descriptor.Descriptor(
  name='TheColorImage',
  full_name='TheColorImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='TheColorImage.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='TheColorImage.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='TheColorImage.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=596,
)


_THEDEPTHIMAGE = _descriptor.Descriptor(
  name='TheDepthImage',
  full_name='TheDepthImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='TheDepthImage.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='TheDepthImage.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='TheDepthImage.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=658,
)


_THEFEELINGS = _descriptor.Descriptor(
  name='TheFeelings',
  full_name='TheFeelings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hunger', full_name='TheFeelings.hunger', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thirst', full_name='TheFeelings.thirst', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exhaustion', full_name='TheFeelings.exhaustion', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='happiness', full_name='TheFeelings.happiness', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=744,
)

_THEUSER.fields_by_name['gender'].enum_type = _THEUSER_GENDER
_THEUSER_GENDER.containing_type = _THEUSER
_THESNAPSHOT.fields_by_name['pose'].message_type = _THEPOSE
_THESNAPSHOT.fields_by_name['color_image'].message_type = _THECOLORIMAGE
_THESNAPSHOT.fields_by_name['depth_image'].message_type = _THEDEPTHIMAGE
_THESNAPSHOT.fields_by_name['feelings'].message_type = _THEFEELINGS
_THEPOSE_THETRANSLATION.containing_type = _THEPOSE
_THEPOSE_THEROTATION.containing_type = _THEPOSE
_THEPOSE.fields_by_name['translation'].message_type = _THEPOSE_THETRANSLATION
_THEPOSE.fields_by_name['rotation'].message_type = _THEPOSE_THEROTATION
DESCRIPTOR.message_types_by_name['TheUser'] = _THEUSER
DESCRIPTOR.message_types_by_name['TheSnapshot'] = _THESNAPSHOT
DESCRIPTOR.message_types_by_name['ThePose'] = _THEPOSE
DESCRIPTOR.message_types_by_name['TheColorImage'] = _THECOLORIMAGE
DESCRIPTOR.message_types_by_name['TheDepthImage'] = _THEDEPTHIMAGE
DESCRIPTOR.message_types_by_name['TheFeelings'] = _THEFEELINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TheUser = _reflection.GeneratedProtocolMessageType('TheUser', (_message.Message,), dict(
  DESCRIPTOR = _THEUSER,
  __module__ = 'cortex_server_pb2'
  # @@protoc_insertion_point(class_scope:TheUser)
  ))
_sym_db.RegisterMessage(TheUser)

TheSnapshot = _reflection.GeneratedProtocolMessageType('TheSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _THESNAPSHOT,
  __module__ = 'cortex_server_pb2'
  # @@protoc_insertion_point(class_scope:TheSnapshot)
  ))
_sym_db.RegisterMessage(TheSnapshot)

ThePose = _reflection.GeneratedProtocolMessageType('ThePose', (_message.Message,), dict(

  TheTranslation = _reflection.GeneratedProtocolMessageType('TheTranslation', (_message.Message,), dict(
    DESCRIPTOR = _THEPOSE_THETRANSLATION,
    __module__ = 'cortex_server_pb2'
    # @@protoc_insertion_point(class_scope:ThePose.TheTranslation)
    ))
  ,

  TheRotation = _reflection.GeneratedProtocolMessageType('TheRotation', (_message.Message,), dict(
    DESCRIPTOR = _THEPOSE_THEROTATION,
    __module__ = 'cortex_server_pb2'
    # @@protoc_insertion_point(class_scope:ThePose.TheRotation)
    ))
  ,
  DESCRIPTOR = _THEPOSE,
  __module__ = 'cortex_server_pb2'
  # @@protoc_insertion_point(class_scope:ThePose)
  ))
_sym_db.RegisterMessage(ThePose)
_sym_db.RegisterMessage(ThePose.TheTranslation)
_sym_db.RegisterMessage(ThePose.TheRotation)

TheColorImage = _reflection.GeneratedProtocolMessageType('TheColorImage', (_message.Message,), dict(
  DESCRIPTOR = _THECOLORIMAGE,
  __module__ = 'cortex_server_pb2'
  # @@protoc_insertion_point(class_scope:TheColorImage)
  ))
_sym_db.RegisterMessage(TheColorImage)

TheDepthImage = _reflection.GeneratedProtocolMessageType('TheDepthImage', (_message.Message,), dict(
  DESCRIPTOR = _THEDEPTHIMAGE,
  __module__ = 'cortex_server_pb2'
  # @@protoc_insertion_point(class_scope:TheDepthImage)
  ))
_sym_db.RegisterMessage(TheDepthImage)

TheFeelings = _reflection.GeneratedProtocolMessageType('TheFeelings', (_message.Message,), dict(
  DESCRIPTOR = _THEFEELINGS,
  __module__ = 'cortex_server_pb2'
  # @@protoc_insertion_point(class_scope:TheFeelings)
  ))
_sym_db.RegisterMessage(TheFeelings)


# @@protoc_insertion_point(module_scope)
